# Site settings
title: Jeremy Hay
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Personal website of Jeremy Hay.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jhay.net" # the base hostname & protocol for your site
twitter_username: robotfood83
github_username:  jeremypepper

# Build settings
markdown: kramdown
